## For påmeldinger av et lag til turnering
id: cosplay
numeric_id: 22
navn: Cosplay
type: gruppe
kategori: vise
frist: 1
har:
  # Dersom minst èn av disse (unntatt media) er true, må vi ha en oversettelsesfil i Delta!
  beskrivelse: true
  varighet: false
  sjanger: false
  tekniske_behov: false
  titler: false
  funksjon: false
  nominasjon: false
  media:
    filmer: true
    bilder: true
er_scene: false
tekst:
  artistnavn:
    alene:
      navn: Hva heter karakteren(e) eller serien den kommer fra?
      placeholder: Eks. "Sailor Moon", "Spiderman"
    sammen:
      navn: Hva heter karakteren(e) eller serien den kommer fra?
      placeholder: Eks. "Prinsesse Bubblegum", "Spiderman", "Sailor Moon" 
  rolle:
    navn: Hvilken karakter spiller denne personen?
    placeholder: F.eks "Sailor Moon", "Prinsesse Bubblegum"
    hjelp: " " 
    ukjent: Ukjent rolle