## For påmeldinger av et lag til turnering
id: dataspillgruppe
numeric_id: 21
navn: Dataspill
type: gruppe
kategori: vise
frist: 1
har:
  # Dersom minst èn av disse (unntatt media) er true, må vi ha en oversettelsesfil i Delta!
  beskrivelse: true
  varighet: false
  sjanger: false
  tekniske_behov: false
  titler: false
  funksjon: false
  nominasjon: false
  media:
    filmer: false
    bilder: true
personer_autofollow: true

tekst:
  artistnavn:
    alene:
      navn: Navn
      placeholder: Eks. [FaZe] %fornavn
    sammen:
      navn: Lagnavn 
      placeholder: Eks. FaZe, Sweaty
    kontakt:
      navn: Lagnavn
      placeholder: Eks. FaZe, Sweaty
  rolle:
    navn: Rolle
    placeholder: F.eks lagleder, top lane etc
    hjelp: " "
    ukjent: Ukjent rolle