id: konferansier
numeric_id: 4
navn: Konferansier
type: person
kategori: jobbe
frist: 2
har:
  beskrivelse: true
  varighet: false
  sjanger: false
  tekniske_behov: false
  titler: false
  funksjon: false
  nominasjon: true
  media:
    filmer: true
    bilder: true

tekst:
  rolle:
    navn: Beskrivelse av deg og din konferansier-erfaring