id: litteratur
numeric_id: 1
navn: Litteratur
type: gruppe
har:
  sjanger: true
  tekniske_behov: true
  titler: true
  funksjon: false
  media:
    filmer: true
    bilder: true
  titler:
    tabell: smartukm_titles_scene

tekst:
  rolle:
    navn: Hva har %person bidratt med til verket / gjør i fremførelsen?
    placeholder: F.eks oppleser, forfatter kapittel 1, korrekturleser...
    hjelp: " "
    ukjent: Ukjent rolle. Trykk her
  titler:
    pronomen: en / et
    entall: tekst / verk
    flertall: tekster / verk
    bestemt: tekstene / verket
    placeholder: Eks. Hobbiten, Enders Game, Paper Towns osv...
  sjanger:
    navn: Sjanger
    placeholder: Eks. dikt, novellesamling, manus osv...
  artistnavn:
    alene:
      navn: Forfatter
      placeholder: Eks. Forfatter-Frank, %fornavn %etternavn...
    sammen:
      navn: Navn på forfattergruppe / forfatter
      placeholder: Eks. Litteraturklubben, Kreative Skribenter fra Hamar...
    kontakt:
      navn: Navn på forfattergruppe / forfatter
      placeholder: Eks. Litteraturklubben, Kreative Skribenter fra Hamar...
