id: matkultur
numeric_id: 6
navn: Matkultur
type: gruppe
kategori: vise
frist: 1
har:
  beskrivelse: true
  varighet: false
  sjanger: false
  tekniske_behov: false
  titler: true
  funksjon: true
  nominasjon: false
  media:
    filmer: true
    bilder: true
er_scene: false
titler:
  tabell: smartukm_titles_other
personer_autofollow: false

tekst:
  rolle:
    navn: Rolle / funksjon
    placeholder: F.eks kokk, konditor
    hjelp: Skriv inn hva %person gjør
    ukjent: Ukjent rolle / funksjon
  titler:
    pronomen: en
    entall: tittel/navn på det som skal fremføres
    flertall: titler/navn på det som skal fremføres
    bestemt: tittelen/navnet på det som skal fremføres
    placeholder: Eks. Banankake-muffins, pannekake-mix osv..
  sjanger:
    navn: sjanger
    placeholder: Eks. Baking
  artistnavn:
    alene:
      navn: Navn / gruppenavn
      placeholder: Eks. Kokke-%fornavn, Kokkegjengen
    sammen:
      navn: Gruppenavn
      placeholder: Eks. Kokkegjengen