id: musikk
numeric_id: 1
navn: Musikk
type: gruppe
kategori: vise
frist: 1
har:
  beskrivelse: true
  varighet: true
  sjanger: true
  tekniske_behov: true
  titler: true
  funksjon: true
  media:
    filmer: true
    bilder: true
er_scene: true
titler:
  tabell: smartukm_titles_scene
personer_autofollow: true

tekst:
  rolle:
    navn: Instrument
    placeholder: F.eks vokal, bass, gitar
    hjelp: Skriv inn hva %person spiller/gjør
    ukjent: Ukjent instrument
  titler:
    pronomen: en
    entall: låt
    flertall: låter
    bestemt: låten
    placeholder: Eks. Skyfall, Utadæsjælåplevelse osv...
  sjanger:
    navn: sjanger
    placeholder: Eks hardrock, visesang...
  artistnavn:
    alene:
      navn: Artistnavn / gruppenavn
      placeholder: Eks. Superbandet, %fornavn %etternavn, %etternavn-band...
    sammen:
      navn: Gruppenavn / artistnavn
      placeholder: Eks. Superbandet, %fornavn and the others...