id: ressurs
numeric_id: 10
navn: Ressurs
type: person
kategori: jobbe
frist: 2
har:
  beskrivelse: true
  varighet: false
  sjanger: false
  tekniske_behov: false
  titler: false
  funksjon: false
  media:
    filmer: true
    bilder: true

tekst:
 - null