id: scene
numeric_id: 1
navn: Annet på scene
type: gruppe
kategori: vise
frist: 1
har:
  beskrivelse: true
  varighet: true
  sjanger: true
  tekniske_behov: true
  titler: true
  funksjon: true
  media:
    filmer: true
    bilder: true
titler:
  tabell: smartukm_titles_scene
personer_autofollow: true

tekst:
  rolle:
    navn: Rolle
    placeholder: F.eks sjonglør, danser, skuespiller osv
    hjelp: Skriv inn hva %person spiller/gjør
    ukjent: Ukjent rolle
  titler:
    pronomen: en
    entall: tittel/navn på det som skal fremføres
    flertall: titler/navn på det som skal fremføres
    bestemt: tittelen/navnet på det som skal fremføres
    placeholder: Eks. Stacking 1-2-3, BMX-cycle, Banankake-kasting osv..
  sjanger:
    navn: sjanger
    placeholder: Eks sjonglering, flammeblåsing...
  artistnavn:
    alene:
      navn: Artistnavn / gruppenavn
      placeholder: Eks. Sjonglør-%fornavn, Sjonglørgruppa, %fornavn %etternavn, %etternavn Stacking osv...
    sammen:
      navn: Gruppenavn / artistnavn
      placeholder: Eks. Sjonglørgruppa, %etternavn og de andre stackerne..