id: teater
numeric_id: 1
navn: Teater
type: gruppe
kategori: vise
frist: 1
har:
  beskrivelse: true
  varighet: true
  sjanger: true
  tekniske_behov: true
  titler: true
  funksjon: true
  media:
    filmer: true
    bilder: true
titler:
  tabell: smartukm_titles_scene

tekst:
  rolle:
    navn: Hva spiller eller gjør %person?
    placeholder: F.eks hovedperson, Operafantomet, skuespiller osv...
    hjelp: " "
    ukjent: Ukjent rolle
  titler:
    pronomen: en
    entall: sketsj/stykke
    flertall: sketsjer/stykker
    bestemt: sketsjen/stykket
    placeholder: Eks. Karlson på taket, Putti plutti pott osv...
  sjanger:
    navn: Sjanger
    placeholder: Eks. monolog, revy osv...
  artistnavn:
    alene:
      navn: Artistnavn
      placeholder: Eks. Teater-%fornavn, %fornavn %etternavn osv...
    sammen:
      navn: Gruppenavn
      placeholder: Eks. Teaterteamet, ImprovGjengen, %etternavn-truppen osv...
    kontakt:
      navn: Gruppenavn / artistnavn
      placeholder: Eks. Teaterteamet, ImprovGjengen, %etternavn-truppen osv...
