id: utstilling
numeric_id: 3
navn: Utstilling
type: gruppe
kategori: vise
frist: 1
har:
  beskrivelse: true
  varighet: false
  sjanger: false
  tekniske_behov: false
  titler: true
  funksjon: true
  nominasjon: false
  media:
    filmer: false
    bilder: true
er_scene: false
titler:
  tabell: smartukm_titles_exhibition
personer_autofollow: false

tekst:
  rolle:
    navn: Skriv inn hvilken rolle %person har, eller hva %person gjør
    placeholder: F.eks maler, tegner, illustratør, skulptør osv.
    hjelp: ''
    ukjent: Ukjent rolle
  titler:
    pronomen: en
    entall: kunst
    flertall: kunstverk
    bestemt: kunstverket/utstillingsobjektet
    placeholder: F.eks. Elg i Solnedgang, Vakker bru osv.
  sjanger:
    navn: Type og teknikk
    placeholder: F.eks. portrettfoto, akvarellmaling, acryl osv.
  artistnavn:
      alene:
          navn: Navn / kunstnernavn / navn på gruppe
          placeholder: F.eks. Kunst-%fornavn, Kunstgjengen fra %etternavn, %fornavn %etternavn...
      sammen:
          navn: Kunstnernavn / navn på gruppe
          placeholder: F.eks. Kunstlinja, painting cowboys, %etternavn-gjengen...