id: utstilling
numeric_id: 3
navn: Utstilling
type: gruppe
kategori: vise
frist: 1
har:
  beskrivelse: true
  varighet: false
  sjanger: false
  tekniske_behov: false
  titler: true
  funksjon: true
  media:
    filmer: false
    bilder: true
titler:
  tabell: smartukm_titles_exhibition

tekst:
  rolle:
    navn: Skriv inn hvilken rolle %person har, eller hva %person gjør
    placeholder: F.eks maler, tegner, illustratør, skulptør osv...
    hjelp: ''
    ukjent: Ukjent rolle
  titler:
    pronomen: et
    entall: verk/utstillingsobjekt
    flertall: verk
    bestemt: verket/utstillingsobjektet
    placeholder: Eks. Elg i Solnedgang, Vakker bru osv...
  sjanger:
    navn: Type og teknikk
    placeholder: Eks. portrettfoto, akvarellmaling, acryl osv.
  artistnavn:
      alene:
          navn: Navn / kunstner-navn
          placeholder: Eks. Kunst-%fornavn, %fornavn %etternavn...
      sammen:
          navn: Kunstnernavn / navn på gruppe
          placeholder: Eks. Kunstlinja, painting cowboys, %etternavn-gjengen...
      kontakt:
          navn: Kunstnernavn / navn på gruppe
          placeholder: Eks. Kunstlinja, painting cowboys, tegneklassen...