name: ukmlib-ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: UKM

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2
        extensions: mbstring
        ini-values: post_max_size=256M, log_errors=1

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: UKM
    
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: UKM

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      working-directory: UKM
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Run test suite
      run: composer run-script test
      working-directory: UKM